name: Continuous Integration

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: preetjdp/typescript-coverage-report@Add-Github-Action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
